require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'views/**/*'
    - 'config/initializers/devise.rb'
  TargetRubyVersion: 3.0.0
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 17

Metrics/ClassLength:
  Enabled: 191

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*'

Lint/RedundantSafeNavigation:
  Enabled: false
